---
Organizations:

  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/veritaschain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer0.veritaschain.com:7050

  - &VoltRideOrg
    Name: VoltRideOrg
    ID: VoltRideMSP
    MSPDir: ../organizations/peerOrganizations/voltride.veritaschain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('VoltRideMSP.admin', 'VoltRideMSP.peer', 'VoltRideMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('VoltRideMSP.admin', 'VoltRideMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('VoltRideMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('VoltRideMSP.peer')"
  - &BatteryOrg
    Name: BatteryOrg
    ID: BatteryMSP
    MSPDir: ../organizations/peerOrganizations/battery.veritaschain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BatteryMSP.admin', 'BatteryMSP.peer', 'BatteryMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BatteryMSP.admin', 'BatteryMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BatteryMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BatteryMSP.peer')"
  - &MotorOrg
    Name: MotorOrg
    ID: MotorMSP
    MSPDir: ../organizations/peerOrganizations/motor.veritaschain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MotorMSP.admin', 'MotorMSP.peer', 'MotorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MotorMSP.admin', 'MotorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MotorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MotorMSP.peer')"
  - &ChassisOrg
    Name: ChassisOrg
    ID: ChassisMSP
    MSPDir: ../organizations/peerOrganizations/chassis.veritaschain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ChassisMSP.admin', 'ChassisMSP.peer', 'ChassisMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ChassisMSP.admin', 'ChassisMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ChassisMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ChassisMSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer0.veritaschain.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer0.veritaschain.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/veritaschain.com/orderers/orderer0.veritaschain.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/veritaschain.com/orderers/orderer0.veritaschain.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Organizations:
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:

  VoltrideBattery:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *VoltRideOrg
          AnchorPeers:
            - Host: peerbattery.voltride.veritaschain.com
              Port: 11051
        - <<: *BatteryOrg
          AnchorPeers:
            - Host: peer0.battery.veritaschain.com
              Port: 7051
      Capabilities: *ApplicationCapabilities
  VoltrideMotor:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *VoltRideOrg
          AnchorPeers:
            - Host: peermotor.voltride.veritaschain.com
              Port: 12051
        - <<: *MotorOrg
          AnchorPeers:
            - Host: peer0.motor.veritaschain.com
              Port: 9051
      Capabilities: *ApplicationCapabilities
  VoltrideChassis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *VoltRideOrg
          AnchorPeers:
            - Host: peerchassis.voltride.veritaschain.com
              Port: 13051
        - <<: *ChassisOrg
          AnchorPeers:
            - Host: peer0.chassis.veritaschain.com
              Port: 10051
      Capabilities: *ApplicationCapabilities
