#!/usr/bin/env node
'use strict';

/**
 * VeritasChain config generator.
 * Reads network/config/platform.json and writes:
 *   - network/docker/docker-compose-ca.yaml   (orderer CA only)
 *   - network/docker/docker-compose-network.yaml (orderer container only)
 *   - network/config/platform.sh              (sourced by bash scripts)
 *
 * Org CAs and peers are started dynamically by the backend API when orgs register.
 * Per-channel configtx.yaml is generated dynamically by backend/src/fabric/configGenerator.js.
 *
 * To bootstrap the platform: run startNetwork.sh (orderer only).
 * To add a new org: POST /orgs/register — the API handles everything.
 */

const fs   = require('fs');
const path = require('path');

const NETWORK_DIR = path.resolve(__dirname, '..');
const platform    = JSON.parse(fs.readFileSync(path.join(NETWORK_DIR, 'config', 'platform.json'), 'utf8'));

const { domain, orderer, chaincode } = platform;

// ── 1. docker-compose-ca.yaml  (orderer CA only) ─────────────────────────────

const caYaml = `networks:
  veritaschain:
    name: veritaschain

services:

  ca_orderer:
    image: hyperledger/fabric-ca:latest
    container_name: ${orderer.caName}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=${orderer.caName}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=${orderer.caPort}
    ports:
      - "${orderer.caPort}:${orderer.caPort}"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/${orderer.folderName}:/etc/hyperledger/fabric-ca-server
    networks:
      - veritaschain
`;

// ── 2. docker-compose-network.yaml  (orderer only) ────────────────────────────

const ordererHost = `${orderer.name}.${domain}`;

const networkYaml = `name: veritaschain

networks:
  veritaschain:
    name: veritaschain

services:

  ${ordererHost}:
    container_name: ${ordererHost}
    hostname: ${ordererHost}
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${orderer.port}
      - ORDERER_GENERAL_LOCALMSPID=${orderer.mspId}
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${orderer.adminPort}
    working_dir: /root
    command: orderer
    ports:
      - ${orderer.port}:${orderer.port}
      - ${orderer.adminPort}:${orderer.adminPort}
    volumes:
      - ../organizations/ordererOrganizations/${domain}/orderers/${ordererHost}/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/${domain}/orderers/${ordererHost}/tls:/var/hyperledger/orderer/tls
      - ../ledger/${orderer.name}:/var/hyperledger/production
    networks:
      - veritaschain
`;

// ── 3. platform.sh  (orderer variables only) ──────────────────────────────────

const platformSh = `# Auto-generated by generate.js — do not edit directly
# Edit network/config/platform.json and re-run: node scripts/generate.js

PLATFORM_DOMAIN="${domain}"
CC_NAME="${chaincode.name}"
CC_VERSION="${chaincode.version}"
CC_SEQUENCE="${chaincode.sequence}"
CC_PATH="${chaincode.path}"

ORDERER_HOST="${orderer.name}"
ORDERER_DOMAIN="${domain}"
ORDERER_MSP_ID="${orderer.mspId}"
ORDERER_PORT=${orderer.port}
ORDERER_ADMIN_PORT=${orderer.adminPort}
ORDERER_CA_PORT=${orderer.caPort}
ORDERER_CA_NAME="${orderer.caName}"
`;

// ── Write files ───────────────────────────────────────────────────────────────

fs.mkdirSync(path.join(NETWORK_DIR, 'docker'), { recursive: true });
fs.mkdirSync(path.join(NETWORK_DIR, 'config'), { recursive: true });

fs.writeFileSync(path.join(NETWORK_DIR, 'docker', 'docker-compose-ca.yaml'), caYaml);
console.log('  network/docker/docker-compose-ca.yaml');

fs.writeFileSync(path.join(NETWORK_DIR, 'docker', 'docker-compose-network.yaml'), networkYaml);
console.log('  network/docker/docker-compose-network.yaml');

fs.writeFileSync(path.join(NETWORK_DIR, 'config', 'platform.sh'), platformSh);
console.log('  network/config/platform.sh');

console.log('\nGenerated orderer-only configs.');
console.log('Orgs and channels are provisioned dynamically via the API.');
