# Auto-generated by generate.js — do not edit directly
# Edit network/config/platform.json and re-run: node scripts/generate.js

PLATFORM_DOMAIN="veritaschain.com"
CC_NAME="veritasorder"
CC_VERSION="1.0"
CC_SEQUENCE="1"
CC_PATH="../chaincode/order"

ORDERER_HOST="orderer0"
ORDERER_DOMAIN="veritaschain.com"
ORDERER_MSP_ID="OrdererMSP"
ORDERER_PORT=7050
ORDERER_ADMIN_PORT=7053
ORDERER_CA_PORT=11054
ORDERER_CA_NAME="ca-orderer"
