version: '3.7'

networks:
  veritaschain:

services:

  orderer0.veritaschain.com:
    container_name: orderer0.veritaschain.com
    hostname: orderer0.veritaschain.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    working_dir: /root
    command: orderer
    ports:
      - 7050:7050
      - 7053:7053
    volumes:
      - ../organizations/ordererOrganizations/veritaschain.com/orderers/orderer0.veritaschain.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/veritaschain.com/orderers/orderer0.veritaschain.com/tls:/var/hyperledger/orderer/tls
      - ../ledger/orderer0:/var/hyperledger/production
    networks:
      - veritaschain

  peer0.battery.veritaschain.com:
    container_name: peer0.battery.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.battery.veritaschain.com
      - CORE_PEER_ADDRESS=peer0.battery.veritaschain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.battery.veritaschain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.battery.veritaschain.com:7051
      - CORE_PEER_LOCALMSPID=BatteryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peer0.battery.veritaschain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/battery.veritaschain.com/peers/peer0.battery.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/battery.veritaschain.com/peers/peer0.battery.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peer0.battery:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peer0.battery.veritaschain.com:host-gateway"

  peer0.motor.veritaschain.com:
    container_name: peer0.motor.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.motor.veritaschain.com
      - CORE_PEER_ADDRESS=peer0.motor.veritaschain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.motor.veritaschain.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.motor.veritaschain.com:9051
      - CORE_PEER_LOCALMSPID=MotorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peer0.motor.veritaschain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9052:9052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/motor.veritaschain.com/peers/peer0.motor.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/motor.veritaschain.com/peers/peer0.motor.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peer0.motor:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peer0.motor.veritaschain.com:host-gateway"

  peer0.chassis.veritaschain.com:
    container_name: peer0.chassis.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.chassis.veritaschain.com
      - CORE_PEER_ADDRESS=peer0.chassis.veritaschain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.chassis.veritaschain.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.chassis.veritaschain.com:10051
      - CORE_PEER_LOCALMSPID=ChassisMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peer0.chassis.veritaschain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    working_dir: /root
    command: peer node start
    ports:
      - 10051:10051
      - 10052:10052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/chassis.veritaschain.com/peers/peer0.chassis.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/chassis.veritaschain.com/peers/peer0.chassis.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peer0.chassis:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peer0.chassis.veritaschain.com:host-gateway"

  peerbattery.voltride.veritaschain.com:
    container_name: peerbattery.voltride.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peerbattery.voltride.veritaschain.com
      - CORE_PEER_ADDRESS=peerbattery.voltride.veritaschain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerbattery.voltride.veritaschain.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerbattery.voltride.veritaschain.com:11051
      - CORE_PEER_LOCALMSPID=VoltRideMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peerbattery.voltride.veritaschain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    working_dir: /root
    command: peer node start
    ports:
      - 11051:11051
      - 11052:11052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peerbattery.voltride.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peerbattery.voltride.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peerbattery.voltride:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peerbattery.voltride.veritaschain.com:host-gateway"

  peermotor.voltride.veritaschain.com:
    container_name: peermotor.voltride.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peermotor.voltride.veritaschain.com
      - CORE_PEER_ADDRESS=peermotor.voltride.veritaschain.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peermotor.voltride.veritaschain.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peermotor.voltride.veritaschain.com:12051
      - CORE_PEER_LOCALMSPID=VoltRideMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peermotor.voltride.veritaschain.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    working_dir: /root
    command: peer node start
    ports:
      - 12051:12051
      - 12052:12052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peermotor.voltride.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peermotor.voltride.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peermotor.voltride:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peermotor.voltride.veritaschain.com:host-gateway"

  peerchassis.voltride.veritaschain.com:
    container_name: peerchassis.voltride.veritaschain.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peerchassis.voltride.veritaschain.com
      - CORE_PEER_ADDRESS=peerchassis.voltride.veritaschain.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerchassis.voltride.veritaschain.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerchassis.voltride.veritaschain.com:13051
      - CORE_PEER_LOCALMSPID=VoltRideMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODEADDRESS=peerchassis.voltride.veritaschain.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
    working_dir: /root
    command: peer node start
    ports:
      - 13051:13051
      - 13052:13052
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peerchassis.voltride.veritaschain.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/voltride.veritaschain.com/peers/peerchassis.voltride.veritaschain.com/tls:/etc/hyperledger/fabric/tls
      - ../ledger/peerchassis.voltride:/var/hyperledger/production
    networks:
      - veritaschain
    extra_hosts:
      - "peerchassis.voltride.veritaschain.com:host-gateway"
